[service]
name = "go-backend"
env = "production"

# Use Docker to build and run the service
buildCommand = "docker build -t go-backend ."
startCommand = "docker run -p 8080:8080 go-backend"

[deploy]
restartPolicyType = "ALWAYS"
